<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <ProjectReference Include="..\..\src\HILOP.Contracts\HILOP.Contracts.csproj" />
    <ProjectReference Include="..\..\src\HILOP.Providers.Abstractions\HILOP.Providers.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\HILOP.Providers.Simulator\HILOP.Providers.Simulator.csproj" />
  </ItemGroup>
</Project>
