<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\HAP.Presentation\HAP.Presentation.csproj" />
    <ProjectReference Include="..\HAP.Application\HAP.Application.csproj" />
    <ProjectReference Include="..\HAP.Configuration\HAP.Configuration.csproj" />
    <ProjectReference Include="..\HAP.Providers.ActiveDirectory\HAP.Providers.ActiveDirectory.csproj" />
    <ProjectReference Include="..\HAP.Providers.ExchangeOnline\HAP.Providers.ExchangeOnline.csproj" />
    <ProjectReference Include="..\HAP.Providers.ExchangeOnPremises\HAP.Providers.ExchangeOnPremises.csproj" />
    <ProjectReference Include="..\HAP.Providers.Graph\HAP.Providers.Graph.csproj" />
    <ProjectReference Include="..\HAP.Providers.Simulator\HAP.Providers.Simulator.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Workflows\*.json" CopyToOutputDirectory="PreserveNewest" TargetPath="workflows\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
