<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\HAP.Contracts\HAP.Contracts.csproj" />
    <ProjectReference Include="..\HAP.Providers.Abstractions\HAP.Providers.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.DirectoryServices" />
  </ItemGroup>
</Project>
