<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <ProjectReference Include="..\..\src\HILOP.Application\HILOP.Application.csproj" />
    <ProjectReference Include="..\..\src\HILOP.Extensions.Abstractions\HILOP.Extensions.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\HILOP.Providers.ActiveDirectory\HILOP.Providers.ActiveDirectory.csproj" />
    <ProjectReference Include="..\..\src\HILOP.Providers.ExchangeOnline\HILOP.Providers.ExchangeOnline.csproj" />
    <ProjectReference Include="..\..\src\HILOP.Providers.Graph\HILOP.Providers.Graph.csproj" />
  </ItemGroup>
</Project>
