<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\HILOP.Application\HILOP.Application.csproj" />
    <ProjectReference Include="..\HILOP.Contracts\HILOP.Contracts.csproj" />
  </ItemGroup>
</Project>
