<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <ProjectReference Include="..\..\src\HAP.LegacyWorker.Protocol\HAP.LegacyWorker.Protocol.csproj" />
    <ProjectReference Include="..\..\src\HAP.Providers.LegacyPowerShell\HAP.Providers.LegacyPowerShell.csproj" />
  </ItemGroup>
</Project>
